import type {
  SystemInfo,
  AuthStatus,
  ValidateKeyResult,
  VoiceState,
  VoiceStateInfo,
  VoiceTranscriptPayload,
  VoiceErrorPayload,
  Reminder,
  ReminderStatus,
  CreateReminderInput,
  UpdateReminderInput,
  ReminderChangePayload,
  ReminderTriggeredPayload,
  CalendarStatus,
  CalendarConnectionStatus,
  CalendarEvent,
  Memory,
  MemoryType,
  CreateMemoryInput,
  UpdateMemoryInput,
  MemoryChangedPayload,
  ClearDataResult,
  ClearMemoriesResult,
  AppConfig,
  GeneralSettings,
  PersonalizeSettings,
  VoiceSettings,
  ReminderSettings,
  IpcResult,
  CalbyVoiceAPI,
  CalbyRemindersAPI,
  CalbyCalendarAPI,
  CalbyMemoryAPI,
  CalbySettingsAPI,
  CalbyAPI
} from '../../../preload/index.d'

export type {
  SystemInfo,
  AuthStatus,
  ValidateKeyResult,
  VoiceState,
  VoiceStateInfo,
  VoiceTranscriptPayload,
  VoiceErrorPayload,
  Reminder,
  ReminderStatus,
  CreateReminderInput,
  UpdateReminderInput,
  ReminderChangePayload,
  ReminderTriggeredPayload,
  CalendarStatus,
  CalendarConnectionStatus,
  CalendarEvent,
  Memory,
  MemoryType,
  CreateMemoryInput,
  UpdateMemoryInput,
  MemoryChangedPayload,
  ClearDataResult,
  ClearMemoriesResult,
  AppConfig,
  GeneralSettings,
  PersonalizeSettings,
  VoiceSettings,
  ReminderSettings,
  IpcResult,
  CalbyVoiceAPI,
  CalbyRemindersAPI,
  CalbyCalendarAPI,
  CalbyMemoryAPI,
  CalbySettingsAPI,
  CalbyAPI
}

declare global {
  interface Window {
    calby: CalbyAPI
  }
}
